---
title: "Conjuntura Econômica:"

output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    storyboard: true
    theme:
      version: 4
      bootswatch: yeti
---

```{r setup, include=FALSE}
setwd('/home/heitor/ProjetosR/Shiny Porjects/Conjuntura/Conjt_board')

library(flexdashboard)
library(tidyverse)
library(plotly)
library(sidrar)

# Coletas: =====================================
# ipca  - Br   reg - último mês - mensal e ac. ano
c1 <- '/t/7060/n1/all/n7/all/n6/all/v/63,69/p/last%201/c315/7169/d/v63%202,v69%202'
# ipca  - Br   reg - histórico - ac. 12 meses
c2 <- '/t/7060/n1/all/n7/all/n6/all/v/2265/p/all/c315/7169/d/v2265%202'
# ipca - br reg - último mês - peso mensal
c3 <- '/t/7060/n1/all/n7/all/n6/all/v/66/p/last%201/c315/7169,7170,7445,7486,7558,7625,7660,7712,7766,7786/d/v66%204'

# Tratamentos: ================================

## c1 ---
d1 <- get_sidra(api = c1) |> as_tibble()

d1 <- d1 |>
	dplyr::select('Var' = 'Variável', 
				  'Mês',
				  'Valor',
				  'Local' = 'Brasil, Região Metropolitana e Município',
				  'Grupo' = 'Geral, grupo, subgrupo, item e subitem')

d1$Var <- stringr::str_replace(d1$Var,
					 pattern = 'IPCA - Variação ',
					 replacement = 'Var. ')
d1 <- d1 |> dplyr::mutate(Local,
						  'br' = case_when(
						  	Local=="Brasil"~'País',
						  	Local!='Brasil'~'RM'))
d1$br <- d1$br |> as_factor()

## c3 ---
d3 <- get_sidra(api = c3) |> as_tibble()

d3 <- d3 |>
	dplyr::select('Valor',
				  'Local' = 'Brasil, Região Metropolitana e Município',
				  'Grupo' = 'Geral, grupo, subgrupo, item e subitem') |>
	dplyr::filter(!Grupo=='Índice geral') |>
	tidyr::pivot_wider(names_from = Grupo,
					   values_from = Valor)

## c2 ---
d2 <- get_sidra(api = c2) |> as_tibble()

d2 <- d2 |>
	dplyr::select('Var' = 'Variável', 
				  'Mês' = "Mês (Código)",
				  'Valor',
				  'Local' = 'Brasil, Região Metropolitana e Município') |>
	dplyr::filter(!is.na(Valor))

d2$Var <- stringr::str_replace(d2$Var,
					 pattern = 'IPCA - Variação acumulada em',
					 replacement = 'Var. Ac.')

d2$Mês <- d2$Mês |> lubridate::ym()
```

# Visão Geral

# Inflação: Consumidor

## Column {data-width="200"}{.tabset .tabset-fade}

### Variação Mensal

```{r}
g1 <- d1 |>
	dplyr::filter(Var == 'Var. mensal') |>
	plot_ly(x = ~Valor,
			y = ~reorder(Local, Valor),
			type = 'bar',
			orientation = 'h',
			text = ~Valor,
			textposition = 'outside',
			color = ~br,
			colors = c('País' = '#117864',
					   'RM' = '#21618c')) |>
	layout(paper_bgcolor = '#f8f8ff',
		   plot_bgcolor = '#f8f8ff',
		   xaxis = list(title = "Var % Mês",
		   			 showgrid = FALSE,
		   			 showline = FALSE,
		   			 showticklabels = FALSE,
		   			 constrain="domain",
		   			 range = c(0,		   			 		  1.1*max(d1$Valor[d1$Var == 'Var. mensal'])),
		   			 zeroline = FALSE),
		   yaxis = list(title = "",
		   			 showticklabels = TRUE),
		   showlegend = FALSE)
config(g1, displaylogo = FALSE,
	   modeBarButtonsToAdd = list('drawopenpath', 'eraseshape'))

```

### Componentes da Inflação no Mês

```{r}
g3 <- plot_ly(data= d3,
			  y= ~reorder(Local,
			  			d1$Valor[
			  			d1$Var=='Var. mensal']),
			  x= ~`1.Alimentação e bebidas`,
			  type = 'bar',
			  orientation = 'h',
			  marker = list(color = 'rgba(38, 24, 74, 0.8)'),
			  line = list(color = 'rgb(248, 248, 249)', width = 1),
			  name='Alimentação')
	
g3 <- g3 |> add_trace(x = ~`2.Habitação`,
					  marker = list(
			color = 'rgba(204, 204, 255, 0.8)'),
			name='Habitação') 
g3 <- g3 |> add_trace(x = ~`3.Artigos de residência`,
					  marker = list(
			color = 'rgba(100, 149, 237, 0.8)'),
			name='Artigos Residenciais') 
g3 <- g3 |> add_trace(x = ~`4.Vestuário`,
					  marker = list(
			color = 'rgba(64, 224, 208, 0.8)'),
			name='Vestuário') 
g3 <- g3 |> add_trace(x = ~`5.Transportes`,
					  marker = list(
			color = 'rgba(159, 226, 191, 0.8)'),
			name='Transporte') 
g3 <- g3 |> add_trace(x = ~`6.Saúde e cuidados pessoais`,
					  marker = list(
			color = 'rgba(222, 49, 99, 0.8)'),
			name='Saúde e cuidados') 
g3 <- g3 |> add_trace(x = ~`7.Despesas pessoais`,
					  marker = list(
			color = 'rgba(255, 127, 80, 0.8)'),
			name='Despesas pessoais') 
g3 <- g3 |> add_trace(x = ~`8.Educação`,
					  marker = list(
			color = 'rgba(255, 191, 0, 0.8)'),
			name='Educação') 
g3 <- g3 |> add_trace(x = ~`9.Comunicação`,
					  marker = list(
			color = 'rgba(223, 255, 0, 0.8)'),
			name='Comunicação') 
g3 <- g3 |>
	layout(xaxis = list(title = "Participação %",
						showgrid = TRUE,
						showline = FALSE,
						showticklabels = FALSE,
						zeroline = FALSE,
						domain = c(0.15, 1)),
		   yaxis = list(title = "",
		   			 showticklabels = T),
		   barmode = 'stack',
		   paper_bgcolor = 'rgb(248, 248, 255)',
		   plot_bgcolor = 'rgb(248, 248, 255)',
		   showlegend = T,
		   legend = list(orientation = 'h')) 
config(g3, displaylogo = FALSE,
	   modeBarButtonsToAdd = list('drawopenpath', 'eraseshape'))
```


## Column {data-width="800"}

### Variações Ac. no Ano {data-height="500"}

```{r, fig.width=9, fig.height=3}
g2 <- d1 |>
	dplyr::filter(Var == 'Var. acumulada no ano') |>
	plot_ly(y = ~Valor,
			x = ~reorder(Local, Valor),
			type = 'bar',
			orientation = 'v',
			color = ~br,
			colors = c('País' = '#117864',
					   'RM' = '#21618c'),
			text = ~Valor,
			textposition = 'outside') |>
	layout(xaxis = list(title = ""),
		   yaxis = list(title = "Var % Ac. Ano",
		   			 showgrid = FALSE,
		   			 showline = FALSE,
		   			 constrain="domain",
		   			 range = c(0,		   			 		  1.125*max(d1$Valor[d1$Var == 'Var. acumulada no ano'])),
		   			 showticklabels = FALSE,
		   			 zeroline = FALSE),
		   paper_bgcolor = '#f8f8ff',
		   plot_bgcolor = '#f8f8ff',
		   showlegend = F)
config(g2, displaylogo = FALSE,
	   modeBarButtonsToAdd = list('drawopenpath', 'eraseshape'))
```

### Variações Ac. em 12 Meses {data-height="500"}

```{r, fig.width=9, fig.height=3}
g4 <- plot_ly(data = d2,
		x= ~Mês,
		y= ~Valor,
		color = ~Local,
		type = 'scatter',
		mode = 'lines')|>
	layout(xaxis = list(title = "",
						showgrid = F),
		   yaxis = list(title = "Var. % Ac. 12 Meses",
		   			 showgrid = T,
		   			 showline = FALSE,
		   			 showticklabels = T,
		   			 zeroline = FALSE),
		   paper_bgcolor = '#f8f8ff',
		   plot_bgcolor = '#f8f8ff',
		   showlegend = T)

config(g4, displaylogo = FALSE,
	   modeBarButtonsToAdd = list('drawopenpath', 'eraseshape'))
```


# Inflação: Produtor

# Produção

# Emprego

# Fiscal

# Internacional
